run: helpers/hands.cpp poker-equity/poker_equity_calc.cpp
	g++ helpers/hands.cpp poker-equity/poker_equity_calc.cpp -o run_script -std=c++17 -I/usr/local/include -L/usr/local/lib -I/opt/homebrew/include -L/opt/homebrew/lib 

clean:
	rm -f run_script